# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ae7539255b9e03238d90da3f087a178ae0499e4105ea46f80fcc1cf60fec5065806889a2078a7e19be3e45bcff49007ab83f60a1f69879f8c57913e12485eda

test:
  secret_key_base: d435faf4b2399a3363fbdedba79e6ce1c05e04aefe5622e4245c48a7f9570f110e240cee36446b5687d2eb8e2257946f2de45e7be6c3ac91b09905dc3005a159

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
